<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "robotstxt_editor"
 *
 * Auto generated by Extension Builder 2016-05-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Robots.txt Editor',
	'description' => 'A simple robots.txt editor as TYPO3 backend module.',
	'category' => 'module',
	'author' => 'Andreas Hoffmeyer',
	'author_email' => 'hallo@andreas-hoffmeyer.me',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.3.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);